name: null

channels:
  - conda-forge
  - defaults

dependencies:
  - jupyterlab
  - matplotlib
  - pandas
  - pyarrow
  - python
  - scikit-learn
  - xlrd
  - fbprophet
  - plotly
  - statsmodels
  - seaborn
  - bokeh
